name: stress_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zoom_widget: ^0.2.1
  flutter_colorpicker: ^1.0.3
  bottom_navy_bar: ^6.0.0
  get: ^4.6.5
  provider: ^6.0.3
  material_design_icons_flutter: ^5.0.6996
  image: ^3.0.1
  path_provider: ^2.0.11
  localstorage: ^4.0.0+1
  file: ^6.1.3
  charts_flutter: ^0.12.0
  camera: ^0.10.5+2  # Provides camera functionality for video recording
  flutter_bloc: ^8.1.3  # Implements the BLoC pattern for state management
  equatable: ^2.0.5  # Simplifies equality comparisons for objects
  permission_handler: ^10.4.3  # Manages permissions for camera and microphone
  video_player: ^2.7.0  # Displays video playback
  visibility_detector: ^0.4.0+2  # Detects visibility changes of widgets
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  firebase_app_check: ^0.2.1+8
  http: ^1.1.0
  just_audio: ^0.9.37
  cloudinary: ^1.2.0
  intl: ^0.17.0
  rxdart: ^0.27.7
  just_waveform: ^0.0.6
  flutter_dotenv: ^5.2.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  bloc_test: ^9.1.4  # Provides testing utilities for BLoC testing
  mocktail:  # Provides mock objects for unit testing


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/simple/
    - assets/medium/
    - assets/complex/
    - assets/animals/
    - assets/flowers/
    - assets/matters/
    - assets/plants/
    - assets/icons/
    - assets/home/
    - assets/behaviors/
    - assets/fonts/
    - assets/logo.png
    - assets/bg_logo.png
    - .env

  fonts:
    - family: Chocolate
      fonts:
        - asset: assets/fonts/Chocolate.ttf
    - family: PastelColors
      fonts:
        - asset: assets/fonts/PastelColors.ttf
    - family: McLaren
      fonts:
        - asset: assets/fonts/McLaren-Regular.ttf
    - family: EraserIcon
      fonts:
        - asset: assets/fonts/EraserIcon.ttf

