class AssetsConst {
  // static const List<String> animals = [
  //   "bat.jpg",
  //   "bear.webp",
  //   "bear1.webp",
  //   "bear2.webp",
  //   "bee.webp",
  //   "bee1.webp",
  //   "bee2.webp",
  //   "birds.webp",
  //   "cat.jpg",
  //   "cat.webp",
  //   "cat1.webp",
  //   "cow.webp",
  //   "cow1.webp",
  //   "dog.webp",
  //   "dog1.webp",
  //   "dog2.jpg",
  //   "dogs.webp",
  //   "dogs1.jpg",
  //   "elephant.webp",
  //   "elephant1.webp",
  //   "elephant2.webp",
  //   "fox.webp",
  //   "fox1.webp",
  //   "frog.jpg",
  //   "frog1.webp",
  //   "frog2.webp",
  //   "giraffe.webp",
  //   "horse.webp",
  //   "horse1.webp",
  //   "leon.webp",
  //   "leon1.webp",
  //   "leon2.jpg",
  //   "owl.jpg",
  //   "pig.webp",
  //   "pig1.webp",
  //   "rabbit.webp",
  //   "rabbit1.webp",
  //   "rabbit2.webp",
  //   "shark.webp",
  //   "snake.jpg",
  //   "turkey.jpg",
  //   "turtle.webp",
  // ];
  //
  // static const List<String> flowers = [
  //   "flowers.webp",
  //   "flowers1.webp",
  //   "flowers2.webp",
  //   "flowers3.jpg",
  //   "flowers4.webp",
  //   "flowers5.webp",
  //   "flowers6.jpg",
  //   "flowers7.webp",
  //   "flowers8.webp",
  //   "flowers9.webp",
  //   "flowers10.webp",
  //   "flowers11.webp",
  //   "flowers12.jpg",
  // ];
  // static const List<String> matters = [
  //   "hands.webp",
  // ];
  // static const List<String> plants = [
  //   "plants.webp",
  //   "plants1.webp",
  // ];
  static const List<String> simple = [
    "p1.jpg",
    "p2.jpg",
    "p3.jpg",
    "p4.jpg",
    "p5.jpg",
    "p6.jpg",
    "p7.jpg",
    "p8.jpg",
    "p9.jpg",
  ];
  static const List<String> medium = [
    "m1.jpg",
    "m2.jpg",
    "m3.jpg",
    "m4.jpg",
    "m5.jpg",
    "m6.jpg",
    "m7.jpg",
    "m8.jpg",
    "m9.jpg",
  ];
  static const List<String> complex = [
    "c1.jpg",
    "c2.jpg",
    "c3.jpg",
    "c4.jpg",
    "c5.jpg",
    "c6.jpg",
    "c7.jpg",
    "c8.jpg",
  ];
}
